blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='all_blogs'),
    path('<int:blog_id>/', views.blog_detail, name='blog_detail'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.views import index
from authentication.views import signupuser
from blog.urls import urlpatterns as blogurls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', signupuser, name="signup"),
    path('', index, name="index"),
    path('blog/', include('blog.urls')),
]

urlpatterns += blogurls

authentication/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=100)
    bio = models.TextField()
    date = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

blog/forms.py
from django.forms import ModelForm
from .models import Blog


class CreateBlog(ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'bio']

authentication/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.utils import timezone
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
from blog.forms import CreateBlog

# Create your views here.
def signupuser(request):
    if request.method == 'GET':
        return render(request, 'signupuser.html', {'form': UserCreationForm()})
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('all_blogs')
            except IntegrityError:
                return render(request, 'signupuser.html', {'form': UserCreationForm()}, {'error': 'That Username Has Already Been Taken'})
        else:
            return render(request, 'signupuser.html', {'form': UserCreationForm()}, {'error': 'Passwords Did Not Match'})

def loginuser(request):
    if request.method == 'GET':
        return render(request, 'loginuser.html', {'form': AuthenticationForm()})
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'loginuser.html', {'form': AuthenticationForm()}, {'error': 'The Username and Password Did Not Match'}) 
        else:
            login(request, user)
            return redirect('all_blogs') 

@login_required
def logoutuser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('index') 

@login_required
def createblog(request):
    if request.method == 'GET':
        return render(request, 'createblog.html', {'form': CreateBlog()})
    else:
        try:
            form = CreateBlog(request.POST)
            newpost = form.save(commit=False)
            newpost.user = request.user
            newpost.save()
            return redirect('all_blogs')
        except ValueError:
            return render(request, 'createblog.html', {'form': CreateBlog(), 'error': 'Bad Data'})

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Blog
from blog.forms import CreateBlog
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required
def index(request):
    blogs = Blog.objects.filter(user=request.user)
    return render(request, 'index.html', {"blogs": blogs})

@login_required
def view_blog(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id, user=request.user)
    if request.method == 'GET':
        form = CreateBlog(instance=blog)
        return render(request, 'blog_detail.html', {'blog': blog, 'form': form})
    else:
        try:
            form = CreateBlog(request.POST, instance=blog)
            form.save()
            return redirect('blog_detail')
        except ValueError:
            return render(request, 'blog_detail.html', {'blog': blog, 'form': form, 'error': 'Bad Info'})


@login_required
def blog_detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog_detail.html', {'blog': blog})

@login_required
def deleteblog(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id, user=request.user)
    if request.method == 'POST':
        blog.delete()
        return redirect('index')

templates/all_blogs.html
{% extends 'base.html' %}

{% block pagecontent %}
<h1 id ="blogtitle" class="font-weight-bold text-center">Welcome To My Blog Page</h1>
<h2 class="text-center mb-5">Zach has written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h2>


</div>
{% for blog in blogs %}
   <a href="{% url 'blog:detail' blog.id %}"><h2> {{ blog.title }}</h2></a>
   <h5>{{ blog.date|date:'M d Y'|upper }}</h5>
   <p>{{ blog.bio|striptags|truncatechars:100 }}</p>
{% endfor %}

{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com"> 
    <link href="https://fonts.googleapis.com/css2?family=Freckle+Face&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static "custom.css" %}">
    <link rel="icon" type="image/png" href="{% static "color-palette.png" %}">
    <title>Zachary Baca</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <div>
            <h1 style="margin-left: 2%;">Zachary</h1>
            <h1 style="margin-top: 6%;">Baca</h1>
          </div>
          <img src="{% static "paint-brushes.png" %}" style="width:100px;height:110px;">
          <div>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:all_blogs' %}">Blogs</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% static "resume.pdf" %}" tabindex="-1">Resume</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      
      {% block pagecontent %}{% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/blog_detail.html
{% extends 'base.html' %}

{% block pagecontent %}

<h1 id="blogdetailtitle">{{ blog.title }}</h1>

<h2>--{{ blog.date|date:'F jS Y' }}--</h2>

{{ blog.bio|safe }}

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block pagecontent %}


{% load static %}

{{ hello }}

templates/signupuser.html
{% extends 'base.html' %}

{% block content %}




<h1>Sign Up</h1>

<h2>{{ error }}</h2>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>Sign Up</button>
</form>

{% endblock %}